# Generated by Django 5.1.5 on 2025-02-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_tweets", "0003_comment_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="media",
            old_name="created_at",
            new_name="uploaded_at",
        ),
        migrations.RemoveField(
            model_name="media",
            name="tweet",
        ),
        migrations.AddField(
            model_name="tweet",
            name="media",
            field=models.ManyToManyField(
                blank=True, related_name="tweets", to="app_tweets.media"
            ),
        ),
    ]
